### PR TITLE
Format chap00.md

### PR DESCRIPTION
**Pull request by SarveshMD**
Added line breaks in chap00.md for each chapter. It looked cluttered, now a bit better.

### CODE REVIEW

**Comment by csev** [comment]
Thanks.

**Comment by csev** [comment]
In general, I don't want to alter the formatting from the original book - we can definitely make the Markdown cleaner though.  When you change formatting make sure to look at the scanned page to make sure the result is true to the original formatting as much as possible.

**Comment by SarveshMD** [comment]
Sure Dr. Chuck, Will double check next time.

**Comment by SarveshMD** [comment]
BTW, Where can I get a PDF of the original book so that I can check if I am keeping up with the original formatting ?

**Comment by csev** [comment]
There is no original PDF - If you go to https://www.cc4e.com/book/chap01.md - you see the "Page 5" links - these are the scanned images - they are the best we have for an original.  I don't think copyright would allow me to product a complete and downloadable PDF an I don't know of any in existence.

**Comment by SarveshMD** [comment]
Thanks.

**Pull request merged**
