### PR TITLE
Update chap00.md, chap01.md

### PR DESCRIPTION
**Pull request by SarveshMD**
Also updated chap06.md a bit. Completed fixing formatting errors in chap00.md, and half way through chap01.md.

### CODE REVIEW

**Comment by SarveshMD** [comment]
I wanted to leave a question to Dr. Chuck. In many pages of the book, the references to the programming language PL/I is bolded in the markdown files, but I don't think they are bolded in the scanned book. I wanted to ask you if I can change the bolded PL/I to non-bolded in the markdown version of the book, or shall I leave those bolded PL/I alone ?

**Comment by csev** [comment]
Lets take out the bold for PL/I - I agree that while the OCR seemed to detect bold - the original book does not bold these.  You know that you did not have to take back your pull request and resubmit.  If you kept pushing to your branch the PR just updates.  Thanks for restoring the first hello world.   Let me know if the README.md needs improvement - I put it together quickly last night.

**Comment by SarveshMD** [comment]
@csev Thanks. I am very new to working with GitHub repositories, so I didn't know that I could just add another commit to the previous #30 Pull request. I don't think README.md can be any better. I love the way you teach and write stuff. One more thing I wanted to ask you was, in book/code/c_026_01.c, a function is called `get_line`, but in the book, it is `getline` without the underscore in between. Should I change the name to getline or shall I leave it alone ?

**Comment by csev** [comment]
If you ever find a "Yada" - it was something that I was debugging - but forgot to remove.  Please remove them whenever you find them.

The `get_line` is changed to avoid conflict with stdio.h - it (so far) is the only place I had to deviate from the sample code in the book.

**Pull request merged**
